### ISSUE TITLE
Adding Tests

### ISSUE THREAD

**Issue by hoangnatalie** [hoangnatalie/miniCanvas#1]
As a **User**, I want to access a movie app so that I can search a movie I'd like to watch.

**Description**

**Feature Name**: 

**Task List**
- [ ] All the methods in the repository should have at least one unit test
- [ ] The coverage of the tests should be as high as possible
- [ ] Use Mocker to test behaviors appropriately
- [ ] Use fixture to let your tests be as DRY (don't-repeat-yourself) as possible
- [ ] The initial code from the repository is not perfect, make sure to fix any issues that your tests reveal.
- [ ] The final backend app should handle all the invalid inputs and throw appropriate error messages.

**Acceptance Criteria**
- [Insert]

**Acceptance Tests**
**Test 1**
- [Insert]
